# Generated by Django 5.1.7 on 2025-03-18 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('departure_time', models.CharField(max_length=20)),
                ('arrival_time', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=20)),
                ('source', models.CharField(max_length=50)),
                ('flight_number', models.CharField(blank=True, max_length=20, null=True)),
                ('stops', models.IntegerField(default=0)),
                ('aircraft', models.CharField(blank=True, max_length=50, null=True)),
                ('baggage_allowance', models.CharField(blank=True, max_length=50, null=True)),
                ('refundable', models.BooleanField(default=False)),
                ('booking_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='flights.flight')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
