# Generated by Django 5.1.7 on 2025-03-18 23:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_alter_flight_options_remove_flight_aircraft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='aircraft_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='booking_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='cabin_class',
            field=models.CharField(default='Economy', max_length=50),
        ),
        migrations.AddField(
            model_name='flight',
            name='carry_on_included',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='checked_bags_included',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='refundable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flight',
            name='search_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='flight',
            name='seats_available',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='stop_locations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='search_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='flight',
            name='duration',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='flight',
            name='from_location',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='flight',
            name='stops',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flight',
            name='to_location',
            field=models.CharField(max_length=3),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['from_location', 'to_location', 'departure_time'], name='flights_fli_from_lo_7066be_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['price'], name='flights_fli_price_59fecb_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['airline'], name='flights_fli_airline_82a3a1_idx'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['flight', 'recorded_at'], name='flights_pri_flight__b92bc6_idx'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['search_date'], name='flights_pri_search__2df983_idx'),
        ),
    ]
